server:
  port: 8080

spring:
  application:
    name: customer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgres://localhost:5432/customer
    username: 'amigoscode'
    password: 'password'
