server:
  port: 8081

spring:
  application:
    name: fraud

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud
    username: 'amigoscode'
    password: 'password'
